### PR TITLE
Test S3 state backend

### PR DESCRIPTION
**Pull request by kerin**

### CODE REVIEW

**Comment by mojanalytics** [comment]
Ran Plan for dir: `infra/terraform/resources/example` workspace: `default`

**Plan Error**
```
exit status 1: running "sh -c terraform init -input=false -no-color" in "/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/4/default/infra/terraform/resources/example"

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Error loading state: AccessDenied: Access Denied
	status code: 403, request id: 0368033DDB5165E5, host id: Pos8i82jT3ia8PlYvD7HU8k9guqNJMjKT7zgl9kY2naPrbiDW2Uu/UJHSn0ityf3Xj2yAjr8SZU=

```

**Comment by kerin** [comment]
atlantis plan

**Comment by mojanalytics** [comment]
Ran Plan for dir: `infra/terraform/resources/example` workspace: `default`

```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infra/terraform/resources/example`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.global.mojanalytics.xyz/lock?id=ministryofjustice%252Fanalytics-platform-atlantis-example%252Finfra%252Fterraform%252Fresources%252Fexample%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infra/terraform/resources/example`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by mojanalytics** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `infra/terraform/resources/example` workspace: `default`

**Pull request merged**
