### PR TITLE
Test custom env vars in Atlantis workflows

### PR DESCRIPTION
**Pull request by kerin**

### CODE REVIEW

**Comment by kerin** [comment]
atlantis plan

**Comment by mojanalytics** [comment]
Ran Plan for 0 projects:

**Comment by kerin** [comment]
atlantis plan -p test

**Comment by mojanalytics** [comment]
Ran Plan for project: `test` dir: `infra/terraform/resources/example` workspace: `test`

<details><summary>Show Output</summary>

```diff
Env var test -

[0m[32mSwitched to workspace "test".[0m

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.archive_file.hello_world: Refreshing state...
aws_s3_bucket.bucket: Refreshing state... (ID: mojap-atlantis-test-bucket-test)
data.aws_iam_policy_document.hello_world: Refreshing state...
aws_iam_role.hello_world: Refreshing state... (ID: atlantis_hello_world_lambda_test)
aws_lambda_function.hello_world: Refreshing state... (ID: atlantis_hello_world_test)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.global.mojanalytics.xyz/lock?id=ministryofjustice%252Fanalytics-platform-atlantis-example%252Finfra%252Fterraform%252Fresources%252Fexample%252Ftest)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by kerin** [comment]
atlantis plan -p test

**Comment by mojanalytics** [comment]
Ran Plan for project: `test` dir: `infra/terraform/resources/example` workspace: `test`

<details><summary>Show Output</summary>

```diff
Env var test - debug

[0m[32mSwitched to workspace "test".[0m

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.archive_file.hello_world: Refreshing state...
aws_s3_bucket.bucket: Refreshing state... (ID: mojap-atlantis-test-bucket-test)
data.aws_iam_policy_document.hello_world: Refreshing state...
aws_iam_role.hello_world: Refreshing state... (ID: atlantis_hello_world_lambda_test)
aws_lambda_function.hello_world: Refreshing state... (ID: atlantis_hello_world_test)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.global.mojanalytics.xyz/lock?id=ministryofjustice%252Fanalytics-platform-atlantis-example%252Finfra%252Fterraform%252Fresources%252Fexample%252Ftest)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by kerin** [comment]
atlantis plan -p test

**Comment by mojanalytics** [comment]
Ran Plan for project: `test` dir: `infra/terraform/resources/example` workspace: `test`

<details><summary>Show Output</summary>

```diff
Env var test - debug -

[0m[32mSwitched to workspace "test".[0m

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.archive_file.hello_world: Refreshing state...
aws_s3_bucket.bucket: Refreshing state... (ID: mojap-atlantis-test-bucket-test)
data.aws_iam_policy_document.hello_world: Refreshing state...
aws_iam_role.hello_world: Refreshing state... (ID: atlantis_hello_world_lambda_test)
aws_lambda_function.hello_world: Refreshing state... (ID: atlantis_hello_world_test)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.global.mojanalytics.xyz/lock?id=ministryofjustice%252Fanalytics-platform-atlantis-example%252Finfra%252Fterraform%252Fresources%252Fexample%252Ftest)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by kerin** [comment]
atlantis plan -p test

**Comment by mojanalytics** [comment]
Ran Plan for project: `test` dir: `infra/terraform/resources/example` workspace: `test`

<details><summary>Show Output</summary>

```diff
Env var test - debug -

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.archive_file.hello_world: Refreshing state...
aws_s3_bucket.bucket: Refreshing state... (ID: mojap-atlantis-test-bucket-test)
data.aws_iam_policy_document.hello_world: Refreshing state...
aws_iam_role.hello_world: Refreshing state... (ID: atlantis_hello_world_lambda_test)
aws_lambda_function.hello_world: Refreshing state... (ID: atlantis_hello_world_test)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.global.mojanalytics.xyz/lock?id=ministryofjustice%252Fanalytics-platform-atlantis-example%252Finfra%252Fterraform%252Fresources%252Fexample%252Ftest)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by kerin** [comment]
atlantis plan -p test

**Comment by mojanalytics** [comment]
Ran Plan for project: `test` dir: `infra/terraform/resources/example` workspace: `test`

<details><summary>Show Output</summary>

```diff
Env var test - debug - foobar

[0m[32mSwitched to workspace "test".[0m

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.archive_file.hello_world: Refreshing state...
aws_s3_bucket.bucket: Refreshing state... (ID: mojap-atlantis-test-bucket-test)
data.aws_iam_policy_document.hello_world: Refreshing state...
aws_iam_role.hello_world: Refreshing state... (ID: atlantis_hello_world_lambda_test)
aws_lambda_function.hello_world: Refreshing state... (ID: atlantis_hello_world_test)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.global.mojanalytics.xyz/lock?id=ministryofjustice%252Fanalytics-platform-atlantis-example%252Finfra%252Fterraform%252Fresources%252Fexample%252Ftest)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Pull request merged**
