### PR TITLE
Remove lambda function

### PR DESCRIPTION
**Pull request by kerin**

### CODE REVIEW

**Comment by mojanalytics** [comment]
Ran Plan for dir: `infra/terraform/resources/example` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
exit status 1: running "sh -c terraform init -input=false -no-color" in "/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/9/default/infra/terraform/resources/example"
Initializing modules...
- module.s3
  Getting source "../../modules/s3_bucket"

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Error: output 'lambda_sensitive_value': unknown module referenced: lambda_function



Error: output 'lambda_sensitive_value': reference to undefined module "lambda_function"



```
</details>

**Comment by mojanalytics** [comment]
Ran Plan for dir: `infra/terraform/resources/example` workspace: `default`

<details><summary>Show Output</summary>

```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_iam_role.hello_world: Refreshing state... (ID: atlantis_hello_world_lambda)
aws_s3_bucket.bucket: Refreshing state... (ID: mojap-atlantis-test-bucket)
aws_lambda_function.hello_world: Refreshing state... (ID: atlantis_hello_world)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

- module.lambda_function.aws_iam_role.hello_world

  - module.lambda_function.aws_lambda_function.hello_world
Plan: 0 to add, 0 to change, 2 to destroy.

------------------------------------------------------------------------

This plan was saved to: /home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/9/default/infra/terraform/resources/example/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/9/default/infra/terraform/resources/example/default.tfplan"


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infra/terraform/resources/example`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.global.mojanalytics.xyz/lock?id=ministryofjustice%252Fanalytics-platform-atlantis-example%252Finfra%252Fterraform%252Fresources%252Fexample%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infra/terraform/resources/example`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by kerin** [comment]
atlantis apply

**Comment by mojanalytics** [comment]
Ran Apply for dir: `infra/terraform/resources/example` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
exit status 1: running "sh -c terraform apply -input=false -no-color \"/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/9/default/infra/terraform/resources/example/default.tfplan\"" in "/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/9/default/infra/terraform/resources/example"
module.lambda_function.aws_lambda_function.hello_world: Destroying... (ID: atlantis_hello_world)
module.lambda_function.aws_lambda_function.hello_world: Destruction complete after 0s
module.lambda_function.aws_iam_role.hello_world: Destroying... (ID: atlantis_hello_world_lambda)

Error: Error applying plan:

1 error(s) occurred:

* module.lambda_function.aws_iam_role.hello_world (destroy): 1 error(s) occurred:

* aws_iam_role.hello_world: Error listing Profiles for IAM Role (atlantis_hello_world_lambda) when trying to delete: AccessDenied: User: arn:aws:sts::593291632749:assumed-role/atlantis-ecs_task_execution/158e8b3a-ac03-43cf-8b2c-7d0fa69845b7 is not authorized to perform: iam:ListInstanceProfilesForRole on resource: role atlantis_hello_world_lambda
	status code: 403, request id: 421e7646-0f55-11e9-93ee-eb368996dbfb

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.



```
</details>

**Comment by kerin** [comment]
atlantis apply

**Comment by mojanalytics** [comment]
Ran Apply for dir: `infra/terraform/resources/example` workspace: `default`

**Apply Error**
```
exit status 1: running "sh -c terraform apply -input=false -no-color \"/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/9/default/infra/terraform/resources/example/default.tfplan\"" in "/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/9/default/infra/terraform/resources/example"
Failed to load backend: This plan was created against an older state than is current. Please create
a new plan file against the latest state and try again.

Terraform doesn't allow you to run plans that were created from older
states since it doesn't properly represent the latest changes Terraform
may have made, and can result in unsafe behavior.

Plan Serial:    11
Current Serial: 13

```

**Comment by kerin** [comment]
atlantis plan

**Comment by mojanalytics** [comment]
Ran Plan for dir: `infra/terraform/resources/example` workspace: `default`

<details><summary>Show Output</summary>

```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_iam_role.hello_world: Refreshing state... (ID: atlantis_hello_world_lambda)
aws_s3_bucket.bucket: Refreshing state... (ID: mojap-atlantis-test-bucket)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

- module.lambda_function.aws_iam_role.hello_world
Plan: 0 to add, 0 to change, 1 to destroy.

------------------------------------------------------------------------

This plan was saved to: /home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/9/default/infra/terraform/resources/example/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/9/default/infra/terraform/resources/example/default.tfplan"


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infra/terraform/resources/example`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.global.mojanalytics.xyz/lock?id=ministryofjustice%252Fanalytics-platform-atlantis-example%252Finfra%252Fterraform%252Fresources%252Fexample%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infra/terraform/resources/example`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by kerin** [comment]
atlantis apply

**Comment by mojanalytics** [comment]
Ran Apply for dir: `infra/terraform/resources/example` workspace: `default`

```diff
module.lambda_function.aws_iam_role.hello_world: Destroying... (ID: atlantis_hello_world_lambda)
module.lambda_function.aws_iam_role.hello_world: Destruction complete after 1s

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.

```

**Comment by mojanalytics** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `infra/terraform/resources/example` workspace: `default`

**Pull request merged**
