### PR TITLE
Remove lambda function

### PR DESCRIPTION
**Pull request by kerin**

### CODE REVIEW

**Comment by mojanalytics** [comment]
Ran Plan for dir: `infra/terraform/resources/example` workspace: `default`

<details><summary>Show Output</summary>

```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_s3_bucket.bucket: Refreshing state... (ID: mojap-atlantis-test-bucket)
aws_iam_role.hello_world: Refreshing state... (ID: atlantis_hello_world_lambda)
aws_lambda_function.hello_world: Refreshing state... (ID: atlantis_hello_world)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

- module.lambda_function.aws_iam_role.hello_world

  - module.lambda_function.aws_lambda_function.hello_world
Plan: 0 to add, 0 to change, 2 to destroy.

------------------------------------------------------------------------

This plan was saved to: /home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/11/default/infra/terraform/resources/example/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/11/default/infra/terraform/resources/example/default.tfplan"


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infra/terraform/resources/example`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.global.mojanalytics.xyz/lock?id=ministryofjustice%252Fanalytics-platform-atlantis-example%252Finfra%252Fterraform%252Fresources%252Fexample%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infra/terraform/resources/example`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by kerin** [comment]
atlantis apply

**Comment by mojanalytics** [comment]
Ran Apply for dir: `infra/terraform/resources/example` workspace: `default`

```diff
module.lambda_function.aws_lambda_function.hello_world: Destroying... (ID: atlantis_hello_world)
module.lambda_function.aws_lambda_function.hello_world: Destruction complete after 0s
module.lambda_function.aws_iam_role.hello_world: Destroying... (ID: atlantis_hello_world_lambda)
module.lambda_function.aws_iam_role.hello_world: Destruction complete after 1s

Apply complete! Resources: 0 added, 0 changed, 2 destroyed.

```

**Comment by mojanalytics** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `infra/terraform/resources/example` workspace: `default`

**Pull request merged**
