### PR TITLE
Add S3 module

### PR DESCRIPTION
**Pull request by kerin**

### CODE REVIEW

**Comment by mojanalytics** [comment]
Ran Plan for dir: `infra/terraform/resources/example` workspace: `default`

**Plan Failed**: This project is currently locked by an unapplied plan from pull #4. To continue, delete the lock from #4 or apply that plan and merge the pull request.

Once the lock is released, comment `atlantis plan` here to re-plan.

**Comment by kerin** [comment]
atlantis plan

**Comment by mojanalytics** [comment]
Ran Plan for dir: `infra/terraform/resources/example` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

+ module.s3.aws_s3_bucket.bucket
      id:                          <computed>
      acceleration_status:         <computed>
      acl:                         "private"
      arn:                         <computed>
      bucket:                      "mojap-atlantis-test-bucket"
      bucket_domain_name:          <computed>
      bucket_regional_domain_name: <computed>
      force_destroy:               "true"
      hosted_zone_id:              <computed>
      region:                      <computed>
      request_payer:               <computed>
      versioning.#:                <computed>
      website_domain:              <computed>
      website_endpoint:            <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infra/terraform/resources/example`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.global.mojanalytics.xyz/lock?id=ministryofjustice%252Fanalytics-platform-atlantis-example%252Finfra%252Fterraform%252Fresources%252Fexample%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infra/terraform/resources/example`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by mojanalytics** [comment]
Ran Plan for dir: `infra/terraform/resources/example` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

+ module.s3.aws_s3_bucket.bucket
      id:                          <computed>
      acceleration_status:         <computed>
      acl:                         "private"
      arn:                         <computed>
      bucket:                      "mojap-atlantis-test-bucket"
      bucket_domain_name:          <computed>
      bucket_regional_domain_name: <computed>
      force_destroy:               "true"
      hosted_zone_id:              <computed>
      region:                      <computed>
      request_payer:               <computed>
      versioning.#:                <computed>
      website_domain:              <computed>
      website_endpoint:            <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infra/terraform/resources/example`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.global.mojanalytics.xyz/lock?id=ministryofjustice%252Fanalytics-platform-atlantis-example%252Finfra%252Fterraform%252Fresources%252Fexample%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infra/terraform/resources/example`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by kerin** [comment]
atlantis apply

**Comment by mojanalytics** [comment]
Ran Apply for dir: `infra/terraform/resources/example` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
exit status 1: running "sh -c terraform apply -input=false -no-color \"/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/5/default/infra/terraform/resources/example/default.tfplan\"" in "/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/5/default/infra/terraform/resources/example"
module.s3.aws_s3_bucket.bucket: Creating...
  acceleration_status:         "" => "<computed>"
  acl:                         "" => "private"
  arn:                         "" => "<computed>"
  bucket:                      "" => "mojap-atlantis-test-bucket"
  bucket_domain_name:          "" => "<computed>"
  bucket_regional_domain_name: "" => "<computed>"
  force_destroy:               "" => "true"
  hosted_zone_id:              "" => "<computed>"
  region:                      "" => "<computed>"
  request_payer:               "" => "<computed>"
  versioning.#:                "" => "<computed>"
  website_domain:              "" => "<computed>"
  website_endpoint:            "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* module.s3.aws_s3_bucket.bucket: 1 error(s) occurred:

* aws_s3_bucket.bucket: Error creating S3 bucket: AccessDenied: Access Denied
	status code: 403, request id: 995B8B354B95D4C2, host id: 7PfRNhtKCNoch351Ob7/wpAoLf2coNa28o6vgI1VcBYQXg8heE2D0bkqO5nJsU1mD0HIsEn5uPY=

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.



```
</details>

**Comment by kerin** [comment]
atlantis apply

**Comment by mojanalytics** [comment]
Ran Apply for dir: `infra/terraform/resources/example` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
exit status 1: running "sh -c terraform apply -input=false -no-color \"/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/5/default/infra/terraform/resources/example/default.tfplan\"" in "/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/5/default/infra/terraform/resources/example"
module.s3.aws_s3_bucket.bucket: Creating...
  acceleration_status:         "" => "<computed>"
  acl:                         "" => "private"
  arn:                         "" => "<computed>"
  bucket:                      "" => "mojap-atlantis-test-bucket"
  bucket_domain_name:          "" => "<computed>"
  bucket_regional_domain_name: "" => "<computed>"
  force_destroy:               "" => "true"
  hosted_zone_id:              "" => "<computed>"
  region:                      "" => "<computed>"
  request_payer:               "" => "<computed>"
  versioning.#:                "" => "<computed>"
  website_domain:              "" => "<computed>"
  website_endpoint:            "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* module.s3.aws_s3_bucket.bucket: 1 error(s) occurred:

* aws_s3_bucket.bucket: error reading S3 Bucket (mojap-atlantis-test-bucket): Forbidden: Forbidden
	status code: 403, request id: AB1EF8AB58300BE0, host id: fRJjDw/V4GZhMgt33V35fry/JlR3xwDdFIZTdqCZDBhFlmmTt+gely07EA56IUgP2K2I4FA+Eds=

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.



```
</details>

**Comment by kerin** [comment]
atlantis apply

**Comment by mojanalytics** [comment]
Ran Apply for dir: `infra/terraform/resources/example` workspace: `default`

**Apply Error**
```
exit status 1: running "sh -c terraform apply -input=false -no-color \"/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/5/default/infra/terraform/resources/example/default.tfplan\"" in "/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/5/default/infra/terraform/resources/example"
Failed to load backend: This plan was created against an older state than is current. Please create
a new plan file against the latest state and try again.

Terraform doesn't allow you to run plans that were created from older
states since it doesn't properly represent the latest changes Terraform
may have made, and can result in unsafe behavior.

Plan Serial:    0
Current Serial: 2

```

**Comment by kerin** [comment]
atlantis plan

**Comment by mojanalytics** [comment]
Ran Plan for dir: `infra/terraform/resources/example` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
exit status 1: running "sh -c terraform plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/5/default/infra/terraform/resources/example/default.tfplan\" -var atlantis_user=\"kerin\" -var atlantis_repo=\"ministryofjustice/analytics-platform-atlantis-example\" -var atlantis_repo_name=\"analytics-platform-atlantis-example\" -var atlantis_repo_owner=\"ministryofjustice\" -var atlantis_pull_num=5" in "/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/5/default/infra/terraform/resources/example"
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_s3_bucket.bucket: Refreshing state... (ID: mojap-atlantis-test-bucket)

Error: Error refreshing state: 1 error(s) occurred:

* module.s3.aws_s3_bucket.bucket: 1 error(s) occurred:

* module.s3.aws_s3_bucket.bucket: aws_s3_bucket.bucket: error getting S3 Bucket CORS configuration: AccessDenied: Access Denied
	status code: 403, request id: B03726F387D15D41, host id: DdA3e7nsfuKt7ESMi3UQiJxR1o3KvLbOLmATWmsR6MzwYikFqeWtqjsrq+qLJqxBEUCc4XmaAAU=



```
</details>

**Comment by kerin** [comment]
atlantis apply

**Comment by mojanalytics** [comment]
Ran Apply for dir: `infra/terraform/resources/example` workspace: `default`

**Apply Error**
```
exit status 1: running "sh -c terraform apply -input=false -no-color \"/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/5/default/infra/terraform/resources/example/default.tfplan\"" in "/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/5/default/infra/terraform/resources/example"
Failed to load backend: This plan was created against an older state than is current. Please create
a new plan file against the latest state and try again.

Terraform doesn't allow you to run plans that were created from older
states since it doesn't properly represent the latest changes Terraform
may have made, and can result in unsafe behavior.

Plan Serial:    0
Current Serial: 2

```

**Comment by kerin** [comment]
atlantis plan

**Comment by mojanalytics** [comment]
Ran Plan for dir: `infra/terraform/resources/example` workspace: `default`

```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infra/terraform/resources/example`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.global.mojanalytics.xyz/lock?id=ministryofjustice%252Fanalytics-platform-atlantis-example%252Finfra%252Fterraform%252Fresources%252Fexample%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infra/terraform/resources/example`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by kerin** [comment]
atlantis apply

**Comment by mojanalytics** [comment]
Ran Apply for dir: `infra/terraform/resources/example` workspace: `default`

```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

```

**Comment by mojanalytics** [comment]
Ran Plan for dir: `infra/terraform/resources/example` workspace: `default`

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

~ module.s3.aws_s3_bucket.bucket
      tags.%:    "0" => "1"
      tags.Name: "" => "mojap-atlantis-test-bucket"
Plan: 0 to add, 1 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infra/terraform/resources/example`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.global.mojanalytics.xyz/lock?id=ministryofjustice%252Fanalytics-platform-atlantis-example%252Finfra%252Fterraform%252Fresources%252Fexample%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infra/terraform/resources/example`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by kerin** [comment]
atlantis apply

**Comment by mojanalytics** [comment]
Ran Apply for dir: `infra/terraform/resources/example` workspace: `default`

```diff
module.s3.aws_s3_bucket.bucket: Modifying... (ID: mojap-atlantis-test-bucket)
  tags.%:    "0" => "1"
  tags.Name: "" => "mojap-atlantis-test-bucket"
module.s3.aws_s3_bucket.bucket: Modifications complete after 1s (ID: mojap-atlantis-test-bucket)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

```

**Comment by mojanalytics** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `infra/terraform/resources/example` workspace: `default`

**Pull request merged**
