### PR TITLE
Reinstate lambda function

### PR DESCRIPTION
**Pull request by kerin**

### CODE REVIEW

**Comment by mojanalytics** [comment]
Ran Plan for dir: `infra/terraform/resources/example` workspace: `default`

<details><summary>Show Output</summary>

```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.archive_file.hello_world: Refreshing state...
aws_s3_bucket.bucket: Refreshing state... (ID: mojap-atlantis-test-bucket)
data.aws_iam_policy_document.hello_world: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ module.lambda_function.aws_iam_role.hello_world
      id:                                <computed>
      arn:                               <computed>
      assume_role_policy:                "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Action\": \"sts:AssumeRole\",\n      \"Principal\": {\n        \"Service\": \"lambda.amazonaws.com\"\n      }\n    }\n  ]\n}"
      create_date:                       <computed>
      force_detach_policies:             "false"
      max_session_duration:              "3600"
      name:                              "atlantis_hello_world_lambda"
      path:                              "/"
      unique_id:                         <computed>

  + module.lambda_function.aws_lambda_function.hello_world
      id:                                <computed>
      arn:                               <computed>
      environment.#:                     "1"
      environment.0.variables.%:         "1"
      environment.0.variables.SENSITIVE: "******"
      filename:                          "/tmp/hello_world.zip"
      function_name:                     "atlantis_hello_world"
      handler:                           "hello_handler"
      invoke_arn:                        <computed>
      last_modified:                     <computed>
      memory_size:                       "128"
      publish:                           "false"
      qualified_arn:                     <computed>
      role:                              "${aws_iam_role.hello_world.arn}"
      runtime:                           "python3.6"
      source_code_hash:                  "eyVzJOaeVkM6Fn2XRRb4PRJMBFdQHqXTuaTJ7YRQPqM="
      source_code_size:                  <computed>
      timeout:                           "300"
      tracing_config.#:                  <computed>
      version:                           <computed>
Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/10/default/infra/terraform/resources/example/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/home/atlantis/.atlantis/repos/ministryofjustice/analytics-platform-atlantis-example/10/default/infra/terraform/resources/example/default.tfplan"


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infra/terraform/resources/example`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.global.mojanalytics.xyz/lock?id=ministryofjustice%252Fanalytics-platform-atlantis-example%252Finfra%252Fterraform%252Fresources%252Fexample%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infra/terraform/resources/example`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by kerin** [comment]
atlantis apply

**Comment by mojanalytics** [comment]
Ran Apply for dir: `infra/terraform/resources/example` workspace: `default`

<details><summary>Show Output</summary>

```diff
module.lambda_function.aws_iam_role.hello_world: Creating...
  arn:                   "" => "<computed>"
  assume_role_policy:    "" => "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Action\": \"sts:AssumeRole\",\n      \"Principal\": {\n        \"Service\": \"lambda.amazonaws.com\"\n      }\n    }\n  ]\n}"
  create_date:           "" => "<computed>"
  force_detach_policies: "" => "false"
  max_session_duration:  "" => "3600"
  name:                  "" => "atlantis_hello_world_lambda"
  path:                  "" => "/"
  unique_id:             "" => "<computed>"
module.lambda_function.aws_iam_role.hello_world: Creation complete after 0s (ID: atlantis_hello_world_lambda)
module.lambda_function.aws_lambda_function.hello_world: Creating...
  arn:                               "" => "<computed>"
  environment.#:                     "" => "1"
  environment.0.variables.%:         "" => "1"
  environment.0.variables.SENSITIVE: "" => "supersecret"
  filename:                          "" => "/tmp/hello_world.zip"
  function_name:                     "" => "atlantis_hello_world"
  handler:                           "" => "hello_handler"
  invoke_arn:                        "" => "<computed>"
  last_modified:                     "" => "<computed>"
  memory_size:                       "" => "128"
  publish:                           "" => "false"
  qualified_arn:                     "" => "<computed>"
  role:                              "" => "arn:aws:iam::593291632749:role/atlantis_hello_world_lambda"
  runtime:                           "" => "python3.6"
  source_code_hash:                  "" => "eyVzJOaeVkM6Fn2XRRb4PRJMBFdQHqXTuaTJ7YRQPqM="
  source_code_size:                  "" => "<computed>"
  timeout:                           "" => "300"
  tracing_config.#:                  "" => "<computed>"
  version:                           "" => "<computed>"
module.lambda_function.aws_lambda_function.hello_world: Still creating... (10s elapsed)
module.lambda_function.aws_lambda_function.hello_world: Creation complete after 16s (ID: atlantis_hello_world)

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

lambda_sensitive_value = <sensitive>

```
</details>

**Comment by mojanalytics** [comment]
Ran Plan for dir: `infra/terraform/resources/example` workspace: `default`

<details><summary>Show Output</summary>

```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.archive_file.hello_world: Refreshing state...
aws_s3_bucket.bucket: Refreshing state... (ID: mojap-atlantis-test-bucket)
data.aws_iam_policy_document.hello_world: Refreshing state...
aws_iam_role.hello_world: Refreshing state... (ID: atlantis_hello_world_lambda)
aws_lambda_function.hello_world: Refreshing state... (ID: atlantis_hello_world)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infra/terraform/resources/example`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.global.mojanalytics.xyz/lock?id=ministryofjustice%252Fanalytics-platform-atlantis-example%252Finfra%252Fterraform%252Fresources%252Fexample%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infra/terraform/resources/example`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by mojanalytics** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `infra/terraform/resources/example` workspace: `default`

**Pull request merged**
