### PR TITLE
Testing Atlantis

### PR DESCRIPTION
**Pull request by kerin**
A test PR for Atlantis

### CODE REVIEW

**Comment by mojanalytics** [comment]
Ran Plan for dir: `.` workspace: `default`

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

+ null_resource.example
      id: <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.global.mojanalytics.xyz/lock?id=ministryofjustice%252Fanalytics-platform-atlantis-example%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by kerin** [comment]
atlantis help

**Comment by mojanalytics** [comment]
```cmake
atlantis
Terraform For Teams

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan   Runs 'terraform plan' for the changes in this pull request.
         To plan a specific project, use the -d, -w and -p flags.
  apply  Runs 'terraform apply' on all unapplied plans from this pull request.
         To only apply a specific plan, use the -d, -w and -p flags.
  help   View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.

**Comment by kerin** [comment]
atlantis plan

**Comment by mojanalytics** [comment]
Ran Plan for dir: `.` workspace: `default`

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

+ null_resource.example
      id: <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.global.mojanalytics.xyz/lock?id=ministryofjustice%252Fanalytics-platform-atlantis-example%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by kerin** [comment]
atlantis apply

**Comment by mojanalytics** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
null_resource.example: Creating...
null_resource.example: Creation complete after 0s (ID: 2107136466807609922)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

**Comment by mojanalytics** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
